# Generated by Django 3.0.8 on 2020-07-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=127)),
                ('message', models.TextField(max_length=255)),
                ('origin', models.URLField()),
                ('arrived_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
